version: '3.7'
services:
  operator-redis:
    image: redis:4.0-alpine
    environment:
      - REDIS_PASSWORD=fubar
    ports:
      - 6381:6379
    command: sh -c 'redis-server --requirepass $${REDIS_PASSWORD}'
    networks:
      - egendata

  operator-postgres:
    image: postgres:11-alpine
    tmpfs: /pgtmpfs
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=egendata
      - PGDATA=/pgtmpfs
    ports:
      - 5435:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresuser -d egendata"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - egendata

  cv-redis:
    image: redis:4.0-alpine
    environment:
      - REDIS_PASSWORD=fubar
    ports:
      - 6382:6379
    command: sh -c 'redis-server --requirepass $${REDIS_PASSWORD}'
    networks:
      - egendata

  operator:
    image: jobtechswe/mydata-operator:latest
    ports:
      - 3000:3000
    working_dir: /app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PGHOST=operator-postgres
      - PGPORT=5432
      - PGUSER=postgresuser
      - PGPASSWORD=postgrespassword
      - PGDATABASE=egendata
      - DATABASE_URL=postgres://postgresuser:postgrespassword@operator-postgres:5432/egendata
      - REDIS=redis://:fubar@operator-redis:6381/
      - HOST=http://${HOST_IP}:3000
      - "PRIVATE_KEY=-----BEGIN RSA PRIVATE KEY-----\nMIICXQIBAAKBgQDgR0M9RBFT26AseaNYy9g5YX+YQhbskFTAp0aCO6h/8xPAOzkd\n7sO+Lqrx4Ljs8iuUTv7JUbx8+ml+7IMKYjpFx4eFQ1kcEW9IL5xSKKcHt2O359cy\n5KbBExqj4Fr2JkmCE+XcMJa5GGOnpNKB92pmJtfOkjVBVQ280n/j8suyCwIDAQAB\nAoGBAMwGqBl86ZJy0nSDN2EZF5ujoXJ+dOJBrogP5CmnYfL7y3Ttq1kakwFY7PPb\nLf+HkrN5ZXj5HVJIb14ihFcW4tBR2EtABhuv2J6ZNx0KnDxUj+mJlb7GNgr5eayI\nUibIu8/eQh2+CGMilI/KR8zlRiHpD8BgttfBaRktGIrzklQJAkEA9C8JgnAGUbPp\n3rc3dEZR6pEcOGI5Fjo3uvhbOYO5oa4tJszNF1Fh1oUmn17J6yoMnh0qPG4snL2B\nOgSB8OCOnwJBAOshovf7obbVZFzQ7ikYImT/pqz7f7eV1+Uv1MRfGsXAc0EAXDrh\nAPiJ5icWkeRDCFxaTAy/8lrDGgDcL2CSoRUCQQCem4L4x91C6rMJaEbL7vU8gL8s\n3JgqGOykNLfElwxXubQ4VKUO9Vywo9JfiIlth+WkOlt53zJ5KRqsXcstdB8PAkAo\nw6IfYA6/Reuqc8Z2dWqxG+lnoAqaZ24Qm+RFTz+y/RR+NnPG+W9Tp4SxTiZo7n4q\nlLUOmNCJj72YXJQSKBmpAkAyDc4PrJ3nFt45BOEnRuXE60Lv3VzLPdWggOLcKTbW\nr6NAWQS0VNdXEmJVmdoKFhJAeUvLrXPtBGqPS7HO6A8A\n-----END RSA PRIVATE KEY-----\n"
    command: sh -c 'node wait-for-postgres && npm run migrate up && npm run start'
    networks:
      - egendata

  app:
    image: jobtechswe/mydata-app:latest
    ports:
      - 1338:1338
    working_dir: /app
    environment:
      - OPERATOR_URL=http://${HOST_IP}:3000
      - PORT=1338
    networks:
      - egendata

  cv:
    image: jobtechswe/mydata-cv
    ports:
      - 4000:4000
    working_dir: /app
    environment:
      - NODE_ENV=development
      - REDIS=redis://:fubar@cv-redis:6379/
      - CLIENT_ID=http://${HOST_IP}:4000
      - OPERATOR_URL=http://${HOST_IP}:3000
      - "PRIVATE_KEY=-----BEGIN RSA PRIVATE KEY-----\nMIICXgIBAAKBgQDIp5d0w4c8v4Wa/tma1DML3hvtXmsLB6sVFzrHagESn7AR00WB\nT6/hln3/YjXs1OcgQTkbXP41Zz8LaP5QYZ9voywrXD7iuaHfABHolhiW3y9p6fD9\nP6oNDvNKoS6zFOO7rqBHU3vZm5wfAPjeDqwtloTwY983fcgKdcyzTzpOjQIDAQAB\nAoGBALGfGYV1KJvv9jdUbhCO03kn7pTbReqHqTyMSa4I+lYgId5FpXtorQsHCxYt\nPAsgFFELK6A7W5SuhrJ1CNri8Bxzh/7gYyj7njBTsjNfuoiK3cIkZBoTvY9K/OB+\nzinNKibWf3SZv9l1qFkaJvaC/+R5DMLb9RXUiWJbhOHqTThJAkEA5i5IOpmUmDl1\nHkYaf1cHbmCdnuQHI1YTlANAk/QsAdzfExK6tsTgIqSq5qd+Q38xtZJQrTvTT6p7\nJX+WQflunwJBAN8pdOrdr1tr1o8m958uLs33zjLk75ScnL+tqlCFEtZTVZWIXScB\n9YVZff5yYONfkuDK0kw631UMSxSA14vL71MCQQCbb+WWrN+LbEGKkAyUsVBzWQsX\noSSw2A+ghBG318tf9qctWhh8E7bHris6VyEMs3f+BTA1y5CG27kNOXteUfJBAkEA\n2QQDwvLaONlhycxnOdE7iujVCQFBSxASDwTff3Ypn2ti6wu1Kt3o2UjyEaNBPVwQ\nBbK3V5JY5OgTi1jQRA6KKQJAQiTQR1sA2xiUhYwF6K4hnojGW1Ew0ZBLND+APkej\nufcVAF5yh+ACYQPUMrgNwgcHFshCEJ9cpePZMotVy7zSFQ==\n-----END RSA PRIVATE KEY-----\n"
      - PORT=4000
    command: sh -c 'npm start'
    networks:
      - egendata

networks:
  egendata:
    driver: bridge
    name: egendata
