version: '3.7'
services:
  operator-redis:
    image: redis:4.0-alpine
    environment:
      - REDIS_PASSWORD=fubar
    ports:
      - 6381:6379
    command: sh -c 'redis-server --requirepass $${REDIS_PASSWORD}'

  operator-postgres:
    image: postgres:11-alpine
    tmpfs: /pgtmpfs
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=egendata
      - PGDATA=/pgtmpfs
    ports:
      - 5435:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresuser -d egendata"]
      interval: 10s
      timeout: 5s
      retries: 5

  cv-redis:
    image: redis:4.0-alpine
    environment:
      - REDIS_PASSWORD=fubar
    ports:
      - 6382:6379
    command: sh -c 'redis-server --requirepass $${REDIS_PASSWORD}'
